# Generated by Django 5.1.3 on 2024-11-23 16:34

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=20, validators=[accounts.validators.NameValidator(message='Should contain only letters')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=20, validators=[accounts.validators.NameValidator(message='Should contain only letters')]),
        ),
    ]
