# Generated by Django 5.1.3 on 2024-11-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='image_url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homework/'),
        ),
    ]
