# Generated by Django 5.1.3 on 2024-11-23 11:32

import homeworks.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0011_homework_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[homeworks.validators.GradeValidator()]),
        ),
    ]
