# Generated by Django 5.1.3 on 2024-11-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='points',
        ),
        migrations.AddField(
            model_name='student',
            name='avg_grade',
            field=models.FloatField(default=0.0),
        ),
    ]
