# Generated by Django 5.1.3 on 2024-12-01 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
