# Generated by Django 5.1.3 on 2024-11-16 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0003_remove_homework_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='student',
        ),
    ]
