# Generated by Django 5.1.3 on 2024-11-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0005_homework_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
