# Generated by Django 5.1.3 on 2024-11-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0006_homework_is_graded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
