# Generated by Django 5.1.3 on 2024-11-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0007_alter_homework_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='image',
            field=models.ImageField(upload_to='homework_images/'),
        ),
    ]
