# Generated by Django 5.1.3 on 2024-11-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0008_alter_homework_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='image_url',
        ),
    ]
