# Generated by Django 5.1.3 on 2024-11-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0009_remove_homework_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'permissions': [('can_grade_homeworks', 'Can grade homeworks')]},
        ),
    ]
